
# from thoughtbot - https://github.com/thoughtbot/dotfiles/blob/master/tmux.conf
# improve colors
set -g default-terminal 'screen-256color'

# you want emoji, don't you?
set -g utf8
set-window-option -g utf8 on

set-option -g status on
set -g status-utf8 on

# soften status bar color from harsh green to light gray
set -g status-bg '#44475a' # From Dracula color palette - 
set -g status-fg '#bd39f9' # https://github.com/zenorocha/dracula-theme#color-palette

# ctrl-s doubles as prefix (ctrl-b)
set -g prefix2 C-s
set -s escape-time 0 # seconds

# renumber windows sequentially after closing any of them
set -g renumber-windows on

set -g status-keys vi
setw -g mode-keys vi
# vim binding for switching panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# by default, use the current directory in a new pane/split/window
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# set history len higher ty ty
set -g history-limit 30000
